<a href="https://colab.research.google.com/github/pranshulab/Data_science_journey/blob/main/01-python/Expirement_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [7]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/01_python/IRIS.csv')

df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [11]:
print(df.shape)

(150, 5)


In [13]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [14]:
print(df['species'].value_counts())

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64


In [16]:
X = df[
    [
        'sepal_length',
        'sepal_width',
        'petal_length',
        'petal_width'
    ]
]

In [17]:
y = df['species']

In [18]:
encoder = LabelEncoder()

y = encoder.fit_transform(y)

print(y[:10])

[0 0 0 0 0 0 0 0 0 0]


In [19]:
print(encoder.classes_)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [21]:
test_size=0.2

In [22]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
scaler.fit_transform(X_train)

array([[-1.72156775, -0.32483982, -1.34703555, -1.32016847],
       [-1.12449223, -1.22612948,  0.41429037,  0.65186742],
       [ 1.14439475, -0.55016223,  0.58474127,  0.25746024],
       [-1.12449223,  0.12580502, -1.29021859, -1.45163753],
       [-0.40800161, -1.22612948,  0.13020555,  0.12599118],
       [ 0.54731923, -1.22612948,  0.6983752 ,  0.91480554],
       [-0.2885865 , -0.77548465,  0.24383948,  0.12599118],
       [ 0.54731923, -0.55016223,  0.75519216,  0.3889293 ],
       [ 2.21913069, -0.0995174 ,  1.32336182,  1.44068178],
       [ 2.21913069,  1.70306192,  1.66426361,  1.30921272],
       [ 2.09971558, -0.0995174 ,  1.60744665,  1.17774366],
       [ 0.18907392, -0.32483982,  0.41429037,  0.3889293 ],
       [-1.00507713, -2.35274155, -0.15387928, -0.268416  ],
       [-0.04975629, -0.77548465,  0.18702251, -0.268416  ],
       [-0.04975629, -1.00080706,  0.13020555, -0.00547788],
       [-1.36332244,  0.35112743, -1.23340162, -1.32016847],
       [-0.88566202,  1.

In [24]:
scaler.transform(X_test)

array([[-1.72156775, -0.0995174 , -1.40385252, -1.32016847],
       [ 0.30848902, -0.0995174 ,  0.64155823,  0.78333648],
       [-1.12449223, -1.45145189, -0.26751321, -0.268416  ],
       [-1.00507713, -1.67677431, -0.26751321, -0.268416  ],
       [-1.72156775,  0.35112743, -1.40385252, -1.32016847],
       [ 0.54731923,  0.57644985,  0.5279243 ,  0.52039836],
       [-1.48273754,  1.25241709, -1.57430342, -1.32016847],
       [-0.52741671,  0.80177226, -1.17658466, -1.32016847],
       [ 0.78614944, -0.0995174 ,  0.81200913,  1.0462746 ],
       [-0.52741671, -0.0995174 ,  0.41429037,  0.3889293 ],
       [ 1.74147027, -0.32483982,  1.43699575,  0.78333648],
       [ 1.26380985,  0.12580502,  0.75519216,  1.44068178],
       [ 0.78614944, -0.0995174 ,  1.15291092,  1.30921272],
       [ 0.66673433,  0.35112743,  0.41429037,  0.3889293 ],
       [-1.00507713,  0.80177226, -1.29021859, -1.32016847],
       [-1.00507713,  0.57644985, -1.34703555, -1.32016847],
       [-0.04975629,  2.

In [25]:
perceptron = Perceptron(
    max_iter=1000,
    random_state=42
)

perceptron.fit(X_train, y_train)

Perceptron(random_state=42)

In [26]:
y_pred_perceptron = perceptron.predict(X_test)

print(y_pred_perceptron)

[0 2 1 1 0 0 0 0 2 1 2 2 2 0 0 0 0 1 1 2 0 2 1 1 2 2 1 0 2 0]


In [27]:
perceptron_test_accuracy = accuracy_score(
    y_test,
    y_pred_perceptron
)

print("Perceptron Testing Accuracy:",
      perceptron_test_accuracy * 100, "%")

Perceptron Testing Accuracy: 86.66666666666667 %


In [28]:
y_train_pred_perceptron = perceptron.predict(X_train)

perceptron_train_accuracy = accuracy_score(
    y_train,
    y_train_pred_perceptron
)

print("Perceptron Training Accuracy:",
      perceptron_train_accuracy * 100, "%")

Perceptron Training Accuracy: 92.5 %


In [29]:
model = Sequential([
    Dense(10, activation='relu', input_shape=(4,)),
    Dense(3, activation='softmax')
])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [30]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [31]:
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=10,
    verbose=1
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8167 - loss: 0.8267
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8167 - loss: 0.7694 
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7833 - loss: 0.7184 
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7917 - loss: 0.6782 
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7917 - loss: 0.6409 
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7917 - loss: 0.6113
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8000 - loss: 0.5863 
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8083 - loss: 0.5630 
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8000 - loss: 0.5439  
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8083 - loss: 0.5266 
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8083 - loss: 0.5109 
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 

In [32]:
train_loss, mlp_train_accuracy = model.evaluate(
    X_train,
    y_train,
    verbose=0
)

print("MLP Training Accuracy:",
      mlp_train_accuracy * 100, "%")

MLP Training Accuracy: 96.66666388511658 %


In [33]:
test_loss, mlp_test_accuracy = model.evaluate(
    X_test,
    y_test,
    verbose=0
)

print("MLP Testing Accuracy:",
      mlp_test_accuracy * 100, "%")

MLP Testing Accuracy: 93.33333373069763 %
