Array operations

In [1]:
import numpy as np

In [5]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1


array([1, 2, 3, 4, 5])

In [8]:
arr2  = a1+a2
arr2

array([ 7,  9, 11, 13, 15])

In [9]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [10]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [11]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [12]:
a1//a2

array([0, 0, 0, 0, 0])

In [13]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Broadcastiong

In [14]:
l = [10,20,30,40,50]
arr = np.array(l)


In [15]:
l + 10

TypeError: can only concatenate list (not "int") to list

In [16]:
arr+10

array([20, 30, 40, 50, 60])

In [17]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and shallow copy

In [45]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [47]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
newa = a[4:6] * 10
newa

array([50, 60])

In [49]:
b = a.copy()

In [50]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [53]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [55]:
A

array([[1, 2],
       [3, 4]])

In [56]:
B

array([[5, 6],
       [7, 8]])

In [57]:
A*B

array([[ 5, 12],
       [21, 32]])

In [58]:
A@B

array([[19, 22],
       [43, 50]])

In [59]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

**Advance Array Manipulation**
Stacking Array

In [65]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [66]:
a

array([1, 2, 3, 4])

In [67]:
b

array([5, 6, 7, 8])

In [69]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Spliting Array

In [73]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [77]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [78]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [79]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]