In [2]:
import numpy as np

**Array indexing and slicing of vectors**

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[6]

np.int64(17)

In [7]:
arr[1:9]

array([12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[:5]

array([11, 12, 13, 14, 15])

In [11]:
arr[1:10:2]

array([12, 14, 16, 18, 20])

**Numpy indexing and slicing of matrix**

In [3]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [4]:
arr[0]

array([1, 2, 3, 4, 5])

In [6]:
arr[5]

array([26, 27, 28, 29, 30])

In [7]:
arr[0,0]

np.int64(1)

In [9]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [11]:
slice= arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [17]:
arr[:,3]

array([ 4,  9, 14, 19, 24, 29])

**bold text**

**BOOLIAN NDEXING**

In [22]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [24]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])